name: GCP Pipeline

on:
  push:
    branches:
      - main

jobs:
  upload-to-gcs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: test-402517
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Authenticate with GCP
      run: echo "${{ secrets.GCP_SA_KEY }}" > $HOME/gcp-key.json && gcloud auth activate-service-account --key-file=$HOME/gcp-key.json

    - name: Upload file to GCS
      run: |
        echo "This is a test file" > test-file.txt
        gsutil cp test-file.txt gs://my-github-actions-bucket-jdl/test-file.txt
