name: GCP Pipeline

on:
  push:
    branches:
      - main

jobs:
  upload-to-gcs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: YOUR_PROJECT_ID
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Authenticate with GCP
      run: gcloud auth activate-service-account --key-file=${{ secrets.GCP_SA_KEY }}

    - name: Upload file to GCS
      run: |
        echo "This is a test file" > test-file.txt
        gsutil cp test-file.txt gs://YOUR_BUCKET_NAME/test-file.txt
