name: GCP Pipeline

on:
  push:
    branches:
      - main

jobs:
  upload-to-gcs:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: pip install requests

    # Step 4: Set up Google Cloud SDK
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: test-402517
        service_account_key: ${{ secrets.SECRET }}
    
    # Step 5: Authenticate with GCP
    - name: Authenticate with GCP
      run: |
        echo "${{ secrets.SECRET }}" > $HOME/gcp-key.json
        gcloud auth activate-service-account --key-file=$HOME/gcp-key.json
    
    # Step 6: Run the Python script
    - name: Run Python script
      run: python fetch_data.py
    
    # Step 7: Upload the file to Google Cloud Storage
    - name: Upload file to GCS
      run: gsutil cp api_response.json gs://my-github-actions-bucket-jdl/api_response.json

    # Step 8: Clean up the service account key file
    - name: Clean up
      run: rm $HOME/gcp-key.json
