name: GCP Pipeline

on:
  push:
    branches:
      - main

jobs:
  upload-to-gcs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: test-402517
        service_account_key: ${{ secrets.SECRET }}
        export_default_credentials: true

    - name: Decode and write service account key to file
      run: |
        echo "${{ secrets.SECRET }}" | base64 --decode > $HOME/gcp-key.json
        echo "=== START OF JSON FILE CONTENT ==="
        cat $HOME/gcp-key.json
        echo "=== END OF JSON FILE CONTENT ==="

    - name: Authenticate with GCP
      run: gcloud auth activate-service-account --key-file=$HOME/gcp-key.json

    - name: Upload file to GCS
      run: |
        echo "This is a test file" > test-file.txt
        gsutil cp test-file.txt gs://my-github-actions-bucket-jdl/test-file.txt
