name: GCP Pipeline

on:
  push:
    branches:
      - main

jobs:
  upload-to-gcs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Write a simple string to file
      run: |
        echo "This is a test string" > ${HOME}/gcp-key.json

    - name: Debug simple string content
      run: |
        echo "=== START OF FILE CONTENT ==="
        cat ${HOME}/gcp-key.json
        echo "=== END OF FILE CONTENT ==="

    - name: Authenticate with GCP (Skipping for now)
      run: gcloud auth activate-service-account --key-file=${HOME}/gcp-key.json
      if: false
